[package]
name = "ckt-garble-service"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
ckt-fmtv5-types.workspace = true
ckt-gobble.workspace = true
ckt-lvl.workspace = true
ckt-runner-exec.workspace = true
rand_chacha.workspace = true

[dev-dependencies]
monoio.workspace = true
rand.workspace = true

[lints]
workspace = true
